FROM python:3.12-slim

WORKDIR /backend

COPY .env .

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY requirements-test.txt .
RUN pip install --no-cache-dir -r requirements-test.txt

COPY . .

CMD ["python", "-m", "pytest", "tests/", "-v"]